### ISSUE TITLE
Requirements are the same for every course

### ISSUE THREAD

**Issue by kungpaogao** [cornell-dti/course-plan#12]
All the course requirements are the same regardless of the semester/course.

<img width="381" alt="Screen Shot 2019-12-10 at 6 23 20 PM" src="https://user-images.githubusercontent.com/11168401/70577895-2e999a80-1b7a-11ea-9d8d-4c145322cf46.png">

**Comment by boonakij** [comment]
The note is just a placeholder, implementation for the popup hasn't been worked on yet.
