### ISSUE TITLE
Existing requirement computation issues

### ISSUE THREAD

**Issue by SamChou19815** [cornell-dti/course-plan#138]
Some of my opinions on how we can make the existing requirement computation more maintainable. None of the issues below should block merging a PR.

### Types of `operator` (`'and' | 'or' | null`) is very confusing.

They don't seem to relate to double counting. A better name would be `requiredCourseCheckerStrategy: 'all-of' | 'any-of'`.

### Bloated `BaseRequirement`

Instead of combining `credits` | `courses` | `self-check` requirements into a single type. We should use TypeScript's disjointed union capability to split them into 3 different types, and do pattern matching on them. In this way, we can get rid of a bunch of `null` and `undefined` possibilibity that are just added for `self-check` types of courses.

### Requirement with several fulfillment strategies

Related to the above issue, we probably should create a new type for requirement like

```typescript
type RequirementWithMultipleFulfillmentStrategy = {
  readonly type: 'RequirementWithMultipleFulfillmentStrategy'
  readonly strategies: readonly Requirement[]
}

type Requirement = 
  | RequirementToBeFulfilledByCourses
  | RequirementToBeFulfilledByCredits
  | RequirementForSelfCheck
  | RequirementWithMultipleFulfillmentStrategy
```

**Comment by willespencer** [comment]
These all look like good improvements! I'll add them to Monday
