### ISSUE TITLE
Incorrect courseplan AP credit logic

### ISSUE THREAD

**Issue by abcdefguan** [cornell-dti/course-plan#397]
My AP credit is not carried over correctly. See gw284@cornell.edu 's account

I input that I have AP credit for:
AP Physics C E&M
AP Physics C Mechanics

These provide AP credit for PHYS 1112 and PHYS 2213

However, my dashboard says that I have not fulfilled any physics courses and need to take PHYS 1112 and PHYS 2213

The same problem occurs for chemistry and mathematics, but I took A level chemistry and got credit for those so I'm not sure how it should work exactly. I did indicate I took the placement test for chemistry and mathematics though

**Comment by tcho6319** [comment]
AP Physics C Mechanics does not seem to be applied to PHYS 1112 still.

**Comment by abcdefguan** [comment]
Issue still not fixed:

AP Microeconomics should be counted as liberal studies
AP Physics C Mechanics should be counted as equivalent of PHYS 1112

**Comment by SamChou19815** [comment]
Both seem to work for me?

<img width="383" alt="Screen Shot 2021-03-31 at 11 03 38" src="https://user-images.githubusercontent.com/4290500/113166443-c5c3af00-9210-11eb-8e72-3c5e63731666.png">

<img width="388" alt="Screen Shot 2021-03-31 at 11 05 09" src="https://user-images.githubusercontent.com/4290500/113166672-ff94b580-9210-11eb-88aa-3f78260d0fba.png">

**Comment by abcdefguan** [comment]
AP Macroeconomics is working for me, but AP Microeconomics is not. AP Physics C Mechanics is not working. 
![Screenshot from 2021-03-31 11-36-48](https://user-images.githubusercontent.com/9957585/113171461-7b90fc80-9215-11eb-8524-bc18194bd7c3.png)

**Comment by tcho6319** [comment]
Yes same here. I'm getting the same issue when I replicated the AP exam data that Guan has

**Comment by SamChou19815** [comment]
Problem confirmed... The core requirement graph algorithm just doesn't like the two courses with the same uniqueId get assigned to the same requirement... This happens to be the case for AP/IB credit where all the unique ID is hardcoded to -1...

**Comment by abcdefguan** [comment]
Yes. It's working now. Awesome.
