### ISSUE TITLE
Incorrect logic for overlapping major and college requirements

### ISSUE THREAD

**Issue by abcdefguan** [cornell-dti/course-plan#398]
CS 1110 / CS 1112 is a single course that counts for 2 requirements. The first requirement is the college computing requirement and the second requirement is the CS major requirement for an introductory programming course. On my (gw284@cornell.edu)'s dashboard, the AP Computer Science A credit for this course is only counted as a single course towards my major requirement and not towards the college requirement.

**Comment by SamChou19815** [comment]
I think the fix for #397 already covers this.

**Comment by abcdefguan** [comment]
Yes this has been fixed
