### ISSUE TITLE
[FEATURE] Core requirement courses fulfill all requirements no matter where they are dragged from

### ISSUE THREAD

**Issue by marcoseiza** [cornell-dti/course-plan#452]
**Description**
I took Math 2930 and MATH 2940. The fulfill the Information Science `Engineering Mathematics` section and also fulfill the Engineering `Mathematics` section.
When I dragged the courses (2930, 2940) from `Engineering Mathematics` in Information Science into my semester card it did not tick off the Engineering `Mathematics` section course.

I would like for the very base level requirements like 2930 and 2940 to fulfill both requirements by default.

I talked to @willespencer about a solution. He asked if having the same modal you get when you manually input a class would be a good solution and I liked that idea.

**Comment by willespencer** [comment]
This has been resolved, at the latest by @benjamin-shen's fix in #638 and pushed to the live site in #634 ! As of now, courses that can fulfill a requirement in both a major and a college will now automatically fulfill both when dragged from the requirements bar.
